sudo: required

services:
    - docker

install:
    docker pull debian:stretch

script:
    docker run -v "$PWD:/workspace/igd-exporter" -w /workspace/igd-exporter debian:stretch './.travis-build.sh'
