dist: trusty
sudo: required
language: generic

services:
    - docker

install:
    docker pull debian:stretch

before_script:
    mkdir igd-exporter && sudo mount --bind "$PWD" igd-exporter

script:
    ./.travis-script.sh

after_script:
    sudo umount igd-exporter
